easyVote/addVote/urls.py
from django.urls import path
from . import views

app_name = "addVote" #specifies that a url name refers to the tasks app (see add.html for implementation)
urlpatterns = [
    path("index", views.index, name="index"),
    path("addNew", views.add, name="addNew"),
    path("", views.results, name="results")
]

easyVote/easyVote/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("addVote.urls")),
]

easyVote/addVote/models.py
from django.db import models
from django.db.models.fields import IntegerField

#SuperUser: Creator/ poponelson@outlook.com / Super...1.
#Register every table at admin.py

# Create your models here.
class Candidate(models.Model):
    name = models.CharField(max_length=64)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.name}: {self.votes} votes"

class Code(models.Model):
    code = models.CharField(max_length=6)
    used = models.BooleanField()

    def __str__(self):
        return f"{self.code}: {self.used} "

easyVote/addVote/views.py
from django.shortcuts import render
import random
import string

#Databases
from .models import Candidate, Code

# Create your views here.
def index(request):
    return render(request, "addVote/newVote.html", {
        "candidates":Candidate.objects.all()
    })

def add(request):
    if request.method == "POST":

        #Check if the code is valid
        userCode = request.POST['code']
        if Code.objects.filter(code=userCode, used=False).exists():
            code = Code.objects.get(code=userCode)
            code.used = True
            code.save()

            #Add the vote
            candidateIds = request.POST.getlist('candidate')
            for id in candidateIds:
                candidate = Candidate.objects.get(pk = int(id))
                candidate.votes += 1
                candidate.save()
            return render(request, "addVote/finished.html", {
                "candidates": Candidate.objects.all(),
            })
        else:
           return render(request, "addVote/newVote.html", {
               "candidates":Candidate.objects.all(),
               "message": "Ο κωδικός αυτός έχει ήδη χρησιμοποιηθεί"
           }) 
    else:
        return render(request, "addVote/newVote.html")

def results(request):
    return render(request, "addVote/finished.html", {
        "candidates": Candidate.objects.all(),
    })

def createCodes():
    created = set()
    i = 0
    while i < 210:
        letters = string.ascii_uppercase
        genCode = ''.join(random.choice(letters) for i in range(6))
        if genCode not in created:
            created.add(genCode)
            newCode = Code(code=genCode, used=False)
            newCode.save()
            i += 1

easyVote/addVote/templates/addVote/finished.html
{% extends "addVote/layout.html" %}

{% block body %}

<div class="container">
    <h2>easyVote</h2>

    {%for cand in candidates%}
        <h5>{{cand}}</h5>
    {%endfor%}
</div>

{% endblock %}

easyVote/addVote/templates/addVote/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="{% static 'addVote/styles.css' %}" rel="stylesheet" />
    <title>easyVote</title>
  </head>

  <body>
    {% block body %}{% endblock %}
  </body>

  <script>
    //Pick up to 5 checkboxes
    var allOptions = document.getElementsByClassName('candOption')


    function checkMax(event) {
      var allChecked = document.querySelectorAll('input[type="checkbox"]:checked');
      if (allChecked.length > 3) {
        alert("Select up to 5 candidates")
        event.target.checked=false;
      }
    }
  </script>
</html>

easyVote/addVote/templates/addVote/newVote.html
{% extends "addVote/layout.html" %}

{% block body %}

<div class="container">
  <h2>easyVote</h2>

  <form action="{% url 'addVote:addNew' %}" method="post">
    
      {% csrf_token %}
    
      {%for cand in candidates%}
      <input type="checkbox" id="{{cand}}" name="candidate" class="candOption" value="{{cand.id}}" onchange="checkMax(event)">
      <label for="{{cand}}">{{cand.name}}</label><br>
      {%endfor%}
      <label for="code">Κωδικός:</label>
      <input type="text" name="code" id="uniqueCode" maxlength="6">
      <input type="submit" id="submitBtn" class="btn btn-primary"/>
  </form>

  {%if message%}
    <h5 class="text-danger">{{message}}</h4>
  {%endif%}
</div>

{% endblock %}